al_ahadeeth/ui/urls.py
"""URLConf for al_ahadeeth.ui"""

from django.urls import path

from al_ahadeeth.ui import views

# Create your URLConf here.
app_name = "al_ahadeeth"

urlpatterns = [
    path("search/", views.SearchView.as_view(), name="search"),
]

al_ahadeeth/ui/views.py
"""Views for al_ahadeeth.ui"""

from typing import Any

from django.views import generic
from wagtail.contrib.search_promotions.models import Query
from wagtail.models import Page


# Create your views here.
class SearchView(generic.ListView):
    """Search View"""

    model = Page
    template_name = "al_ahadeeth/search.html"
    context_object_name = "search_results"
    queryset = Page.objects.live().public()

    def get_context_data(self, **kwargs) -> dict[str, Any]:
        """Search and add to context"""

        return {
            **super().get_context_data(**kwargs),
            "search_query": self.request.GET.get("search", None),
            "search_results": self.get_search_results(),
        }

    def get_search_results(self):
        """Search and return results"""

        queryset = self.get_queryset()
        search_query = self.request.GET.get("search", None)

        search_results = queryset.none()

        if search_query:
            search_results = queryset.search(search_query)

            # Log the query so Wagtail can suggest promoted results
            Query.get(search_query).add_hit()

        return search_results

al_ahadeeth/ui/templates/al_ahadeeth/about.html
{% extends 'ui/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {{ about.title }}{% endblock %}

<!---->
{% block content %}
<section class="container mx-auto px-4 py-20">
  <div
    class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-img:rounded-box prose-img:w-full"
  >
    <h1>{{ about.title }}</h1>
    {{ about.content }}
  </div>
</section>
{% endblock %}

al_ahadeeth/ui/templates/al_ahadeeth/base.html
{% load app i18n static wagtailcore_tags wagtailuserbar %}
<!DOCTYPE html>
<html
  lang="{{ LANGUAGE_CODE }}"
  dir="{% if LANGUAGE_CODE == 'ar' %}rtl{% else %}ltr{% endif %}"
  data-theme="{% block theme %}luxury{% endblock %}"
>
  {% get_site_root as home %}
  <head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% trans 'Al Ahadeeth' %}{% endblock %}</title>
    {% block meta %}{% endblock %}

    <!---->
    {% block styles %}
    <link
      href="{% static 'wagtail_blocks/css/styles.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/daisyui@5"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'al_ahadeeth/css/styles.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/styles/github-dark.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.1/highlight.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js"></script>
    {% endblock %}
    <!---->

    {% endblock %}
  </head>

  <body class="font-sans antialiased">
    {% wagtailuserbar %}

    <div class="drawer">
      <input id="nav-drawer" type="checkbox" class="drawer-toggle" />

      <section id="content" class="drawer-content">
        <div
          id="main"
          class="bg-base-300 relative h-dvh overflow-hidden sm:p-1 lg:p-2"
        >
          <div class="flex size-full items-center gap-1">
            <section
              class="bg-base-100 relative size-full grow overflow-hidden sm:rounded-box"
            >
              <section class="size-full grid gap-4 overflow-y-auto">
                <!-- Navbar -->
                {% block navbar %}
                <header
                  class="absolute inset-x-0 top-0 z-40 px-2 backdrop-blur-3xl lg:px-4"
                >
                  <nav class="navbar py-4">
                    <ol class="navbar-start gap-4">
                      <li
                        class="tooltip tooltip-right rtl:tooltip-left tooltip-primary z-10"
                        data-tip="{% trans 'Open drawer' %}"
                      >
                        <label
                          for="nav-drawer"
                          aria-label="{% trans 'close sidebar' %}"
                          class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
                        >
                          <i data-lucide="menu" class="size-4 md:size-6"></i>
                          <span class="sr-only">
                            {% trans 'Open drawer' %}
                          </span>
                        </label>
                      </li>

                      {% block branding %}
                      <li
                        class="tooltip tooltip-right rtl:tooltip-left tooltip-primary"
                        data-tip="{% trans 'Al Ahadeeth' %}"
                      >
                        <h1 class="relative">
                          <a
                            href="{% pageurl home %}"
                            class="btn btn-square btn-primary lg:btn-lg"
                          >
                            <div
                              class="btn btn-square btn-primary rotate-45 p-0 shadow-none lg:btn-lg"
                            >
                              <i
                                data-lucide="app"
                                class="-rotate-45 lg:size-8 2xl:size-10"
                              ></i>
                            </div>
                            <span class="sr-only">
                              {% trans 'Al Ahadeeth' %}
                            </span>
                          </a>
                        </h1>
                      </li>
                      {% endblock %}
                    </ol>

                    <ol class="navbar-center gap-2">
                      {% block navbar_center %}{% endblock %}
                    </ol>

                    <ol class="navbar-end gap-2">
                      {% block navbar_end %}
                      <li
                        class="tooltip tooltip-left rtl:tooltip-right tooltip-primary"
                        data-tip="{% trans 'Search' %}"
                      >
                        <a
                          href="{% url 'al_ahadeeth:search' %}"
                          class="btn btn-square btn-soft btn-sm btn-primary md:btn-md 2xl:btn-lg"
                        >
                          <i data-lucide="search" class="size-4 md:size-6"></i>
                          <span class="sr-only">{% trans 'Search' %}</span>
                        </a>
                      </li>
                      {% endblock %}
                    </ol>
                  </nav>
                </header>
                {% endblock %}

                <!---->
                {% block content %}
                <div class="container flex flex-col gap-8 px-4 py-20 mx-auto">
                  <div
                    class="mx-auto prose prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-img:rounded-box prose-img:w-full"
                  >
                    <h1>{% trans 'Al Ahadeeth' %}</h1>

                    <p>
                      {% blocktrans trimmed %}A platform to publish Al-Ahadeeth
                      {% endblocktrans %}
                    </p>
                  </div>

                  <ol class="grid grid-cols-12 gap-4">
                    <li
                      role="article"
                      class="card bg-base-100 hover:bg-base-200 border border-base-300 card-sm md:card-md xl:card-lg 2xl:card-xl col-span-12 size-full shadow-sm md:col-span-6 lg:col-span-4 2xl:col-span-3"
                    >
                      <a
                        href="https://github.com/Q-Complex/al-ahadeeth"
                        class="absolute inset-0"
                      >
                        <span class="sr-only">{% trans 'Docs' %}</span>
                      </a>

                      <div class="card-body justify-end">
                        <h2 class="card-title text-primary">
                          <i
                            data-lucide="book-text"
                            class="size-4 md:size-6"
                          ></i>
                          {% trans 'Docs' %}
                        </h2>

                        <p class="grow-0">
                          {% trans 'Get started with Al Ahadeeth' %}
                        </p>
                      </div>
                    </li>
                    <li
                      role="article"
                      class="card bg-base-100 hover:bg-base-200 border border-base-300 card-sm md:card-md xl:card-lg 2xl:card-xl col-span-12 size-full shadow-sm md:col-span-6 lg:col-span-4 2xl:col-span-3"
                    >
                      <a
                        href="https://github.com/Q-Complex/al-ahadeeth#Contributing"
                        class="absolute inset-0"
                      >
                        <span class="sr-only">{% trans 'Contribute' %}</span>
                      </a>

                      <div class="card-body justify-end">
                        <h2 class="card-title text-primary">
                          <i
                            data-lucide="folder-git-2"
                            class="size-4 md:size-6"
                          ></i>
                          {% trans 'Contribute' %}
                        </h2>

                        <p class="grow-0">
                          {% blocktrans trimmed %}Please refer to our
                          CONTRIBUTING guide{% endblocktrans %}
                        </p>
                      </div>
                    </li>
                    <li
                      role="article"
                      class="card bg-base-100 hover:bg-base-200 border border-base-300 card-sm md:card-md xl:card-lg 2xl:card-xl col-span-12 size-full shadow-sm md:col-span-6 lg:col-span-4 2xl:col-span-3"
                    >
                      <a
                        href="https://github.com/Q-Complex/al-ahadeeth/issues"
                        class="absolute inset-0"
                      >
                        <span class="sr-only">{% trans 'Support' %}</span>
                      </a>

                      <div class="card-body justify-end">
                        <h2 class="card-title text-primary">
                          <i
                            data-lucide="heart-handshake"
                            class="size-4 md:size-6"
                          ></i>
                          {% trans 'Support' %}
                        </h2>

                        <p class="grow-0">
                          {% blocktrans trimmed %}For inquiries or support,
                          please open an issue{% endblocktrans %}
                        </p>
                      </div>
                    </li>
                  </ol>
                </div>
                {% endblock %}

                <!---->
                {% block footer %}{% endblock %}
              </section>
            </section>
          </div>
        </div>
      </section>

      <section id="sidebar" class="drawer-side z-50">
        <label
          for="nav-drawer"
          aria-label="{% trans 'close sidebar' %}"
          class="drawer-overlay"
        ></label>

        <section
          class="bg-base-100/75 md:min-w-xs lg:min-w-sm xl:min-w-md 2xl:min-w-lg dark:bg-base-100/50 flex size-full flex-col justify-between overflow-hidden overflow-y-auto backdrop-blur-3xl sm:w-10/12 md:w-8/12 lg:w-1/3 2xl:w-1/4"
        >
          <div class="grid">
            <div class="grid gap-4 p-4">
              <header class="flex items-center justify-between gap-4">
                {% block drawer_branding %}
                <div
                  class="tooltip tooltip-right rtl:tooltip-left tooltip-primary tooltip-open aspect-square"
                  data-tip="{% trans 'Al Ahadeeth' %}"
                >
                  <h1 class="relative">
                    <a
                      href="{% pageurl home %}"
                      class="btn btn-square btn-primary lg:btn-lg"
                    >
                      <div
                        class="btn btn-square btn-primary rotate-45 p-0 shadow-none lg:btn-lg"
                      >
                        <i
                          data-lucide="app"
                          class="-rotate-45 lg:size-8 2xl:size-10"
                        ></i>
                      </div>
                      <span class="sr-only"> {% trans 'Al Ahadeeth' %} </span>
                    </a>
                  </h1>
                </div>
                {% endblock %}

                <div
                  class="tooltip tooltip-left rtl:tooltip-right hover:tooltip-error"
                  data-tip="{% trans 'Close' %}"
                >
                  <label
                    for="nav-drawer"
                    aria-label="{% trans 'close sidebar' %}"
                    class="btn btn-square btn-soft btn-sm btn-primary hover:btn-error md:btn-md 2xl:btn-lg"
                  >
                    <i data-lucide="x" class="size-4 md:size-6"></i>
                    <span class="sr-only">{% trans 'Close' %}</span>
                  </label>
                </div>
              </header>

              <form
                method="get"
                class="join w-full"
                action="{% url 'al_ahadeeth:search' %}"
              >
                <label
                  class="join-item w-full bg-transparent input input-primary"
                >
                  <i
                    data-lucide="search"
                    class="size-4 text-primary md:size-6"
                  ></i>
                  <input
                    required
                    type="search"
                    name="search"
                    class="grow placeholder-primary"
                    placeholder="{% trans 'Search' %}"
                  />
                </label>

                <button
                  type="submit"
                  class="btn join-item btn-square btn-soft btn-primary"
                >
                  <i data-lucide="check-circle2" class="size-4 md:size-6"></i>
                  <span class="sr-only">{% trans 'Search' %}</span>
                </button>
              </form>
            </div>

            <ol class="menu 2xl:menu-lg size-full grow gap-2 overflow-y-auto">
              {% block drawer_content %}
              <li>
                <a href="{% pageurl home %}">
                  <i data-lucide="home" class="size-4 md:size-6"></i>
                  {% trans 'Home' %}
                </a>
              </li>
              <li>
                <a href="https://github.com/Q-Complex/al-ahadeeth">
                  <i data-lucide="folder-git-2" class="size-4 md:size-6"></i>
                  {% trans 'Repo' %}
                </a>
              </li>
              {% for page in home.get_children %}
              <li>
                <a href="{% pageurl page %}">{{ page }}</a>
              </li>
              {% endfor %}
              <!---->
              {% endblock %}
            </ol>
          </div>

          <ol class="grid gap-4 p-4">
            {% block drawer_bottom %}{% endblock %}
          </ol>
        </section>
      </section>
    </div>

    <script src="https://unpkg.com/lucide@latest"></script>
    <script>
      lucide.createIcons();
    </script>
  </body>
</html>

al_ahadeeth/ui/templates/al_ahadeeth/components/breadcrumbs.html
{% load wagtailcore_tags %}

<nav class="breadcrumbs text-primary text-xs lg:text-sm">
  <ol>
    {% for page in page.get_ancestors %}{% if not page.is_root %}
    <li>
      <a href="{% pageurl page %}">{{ page }}</a>
    </li>
    {% endif %}{% endfor %}
    <li>{{ page }}</li>
  </ol>
</nav>

al_ahadeeth/ui/templates/al_ahadeeth/components/form.html
{% load i18n %}

<section class="container mx-auto max-w-xl grid gap-8">
  {% if form.errors %}
  <div class="toast toast-top toast-end top-24 right-8 z-10">
    <ol class="grid gap-4 max-w-2xl mx-auto">
      {% for field, errors in form.errors.items %}
      <li class="alert alert-soft alert-horizontal alert-error">
        <span class="badge badge-error xl:badge-lg">
          <i data-lucide="x-circle" class="size-4 lg:size-6"></i>
          <span>{{ field }}</span>
        </span>

        <div>{{ errors }}</div>
      </li>
      {% endfor %}
    </ol>
  </div>
  {% endif %}

  <form
    enctype="multipart/form-data"
    method="{{ method|default:'post' }}"
    class="grid gap-4"
  >
    {% if csrf|default_if_none:True %}{% csrf_token %}{% endif %}{{ form }}

    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
  </form>
</section>

<script>
  // Style containers and labels
  document
    .querySelectorAll("form > div")
    .forEach((e) => e.classList.add("fieldset"));
  document
    .querySelectorAll("form > div > label")
    .forEach((e) => e.classList.add("fieldset-legend"));
  document
    .querySelectorAll("form > div > .helptext")
    .forEach((e) => e.classList.add("fieldset-label"));

  // Style inputs
  document
    .querySelectorAll("form > div > input")
    .forEach((e) => e.classList.add("input", "input-primary", "w-full"));
  document
    .querySelectorAll("form > div > input[type=checkbox]")
    .forEach((e) => {
      e.classList.remove("input", "w-full");
      e.classList.add("checkbox", "checkbox-primary");
    });
  document.querySelectorAll("form > div > input[type=radio]").forEach((e) => {
    e.classList.remove("input", "w-full");
    e.classList.add("radio", "radio-primary");
  });
  document.querySelectorAll("form > div > input[type=file]").forEach((e) => {
    e.classList.remove("input");
    e.classList.add("file-input");
  });
  document
    .querySelectorAll("form > div > textarea")
    .forEach((e) => e.classList.add("textarea", "textarea-primary", "w-full"));
  document
    .querySelectorAll("form > div > select")
    .forEach((e) => e.classList.add("select", "select-primary", "w-full"));
</script>

al_ahadeeth/ui/templates/al_ahadeeth/components/messages.html
{% if messages %}
<div class="toast toast-top toast-end top-24 right-4 lg:right-24 z-50">
  <ol class="grid gap-4 max-w-2xl mx-auto">
    {% for message in messages %}
    <li class="alert alert-horizontal alert-{{ message.tags }}">
      <i data-lucide="circle-check" class="size-4 lg:size-6"></i>
      <p>{{ message }}</p>
    </li>
    {% endfor %}
  </ol>
</div>
{% endif %}

al_ahadeeth/ui/templates/al_ahadeeth/components/pagination.html
{% load i18n %}

<!---->
<ol class="join flex-wrap">
  {% if page_obj.has_previous %}
  <li
    class="tooltip tooltip-top tooltip-primary"
    data-tip="{% translate 'Previous' %}"
  >
    <a
      href="?page={{ page_obj.previous_page_number }}"
      class="btn join-item btn-primary"
    >
      <i data-lucide="chevron-left" class="size-4 lg:size-6 rtl:rotate-180"></i>
      <span class="sr-only">{% translate 'Previous' %}</span>
    </a>
  </li>

  <li
    class="tooltip tooltip-top tooltip-info"
    data-tip="{% translate 'First' %}"
  >
    <a href="?page=1" class="btn join-item btn-info">
      {% translate 'First' %}
    </a>
  </li>
  {% endif %}

  <li
    class="tooltip tooltip-top tooltip-success"
    data-tip="{% translate 'Current' %}"
  >
    <button class="btn join-item btn-success">
      {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </button>
  </li>

  {% if page_obj.has_next %}
  <li
    class="tooltip tooltip-top tooltip-info"
    data-tip="{% translate 'Last' %}"
  >
    <a
      href="?page={{ page_obj.paginator.num_pages }}"
      class="btn join-item btn-info"
    >
      {% translate 'Last' %}
    </a>
  </li>

  <li
    class="tooltip tooltip-top tooltip-primary"
    data-tip="{% translate 'Next' %}"
  >
    <a
      href="?page={{ page_obj.next_page_number }}"
      class="btn join-item btn-primary"
    >
      <i
        data-lucide="chevron-right"
        class="size-4 lg:size-6 rtl:rotate-180"
      ></i>
      <span class="sr-only">{% translate 'Next' %}</span>
    </a>
  </li>
  {% endif %}
</ol>

al_ahadeeth/ui/templates/al_ahadeeth/contact.html
{% extends 'ui/base.html' %}{% load i18n %}

<!---->
{% block title %}{{ block.super }} | {{ contact.title }}{% endblock %}

<!---->
{% block content %}
<section class="container mx-auto grid gap-8 px-4 py-20">
  {% block message %}{% endblock %}

  <div
    class="prose mx-auto prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-img:rounded-box prose-img:w-full"
  >
    <h1>{{ contact.title }}</h1>
    {{ contact.content }}
  </div>

  {% block form %}
  <div>{% include 'ui/components/form.html' %}</div>
  {% endblock %}
</section>
{% endblock %}

al_ahadeeth/ui/templates/al_ahadeeth/contact_landing.html
{% extends 'ui/contact.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block message %}
<div role="alert" class="alert alert-soft alert-success">
  <div
    class="tooltip tooltip-right rtl:tooltip-left tooltip-success"
    data-tip="{% trans 'Success' %}"
  >
    <span class="btn btn-xs btn-circle btn-success md:btn-sm">
      <i class="size-4 lg:size-6" data-lucide="check-circle2"></i>
      <span class="sr-only">{% trans 'Success' %}</span>
    </span>
  </div>

  {{ contact.message|richtext }}
</div>
{% endblock %}

<!---->
{% block form %}{% endblock %}

al_ahadeeth/ui/templates/al_ahadeeth/index.html
{% extends 'al_ahadeeth/base.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block content %}
<section class="container grid gap-12 mx-auto px-4 py-20">
  {% include 'al_ahadeeth/components/breadcrumbs.html' %}

  <div
    class="mx-auto prose prose-sm prose-video:rounded-box xl:prose-lg 2xl:prose-xl prose-headings:text-primary prose-img:rounded-box prose-img:w-full"
  >
    <h1>{{ index.title }}</h1>

    {{ index.content }}
  </div>
</section>
{% endblock %}

al_ahadeeth/ui/templates/al_ahadeeth/search.html
{% extends 'al_ahadeeth/base.html' %}{% load i18n wagtailcore_tags %}

<!---->
{% block title %}{{ block.super }} | {% trans 'Search' %}{% endblock %}

<!---->
{% block content %}
<div class="container mx-auto grid gap-8 pt-20 px-4">
  <h1 class="text-3xl text-primary font-black lg:text-5xl">
    {% trans 'Search' %}
  </h1>

  <form class="grid gap-4" method="get" action="{% url 'al_ahadeeth:search' %}">
    <label
      class="mx-auto max-w-xl w-full input input-primary xl:input-lg 2xl:input-xl"
    >
      <i
        data-lucide="search"
        class="size-4 text-primary opacity-50 md:size-6 lg:size-8"
      ></i>

      <input
        required
        type="search"
        name="search"
        class="grow"
        placeholder="{% trans 'Search' %}"
        value="{{ search_query|default:'' }}"
      />

      <button type="submit" class="btn btn-sm btn-primary">
        {% trans 'Go' %}
      </button>
    </label>
  </form>

  {% if search_results %}
  <h1 class="text-xl text-primary lg:text-3xl">
    {% trans 'Search results' %} ({{ search_results.count }})
  </h1>

  <ol class="grid grid-cols-12 grid-rows-[auto] gap-4">
    {% for result in search_results %}
    <!---->
    {% include 'al_ahadeeth/components/article.html' with article=result %}
    <!---->
    {% empty %}
    <li>{% trans 'No results found' %}</li>
    {% endfor %}
  </ol>

  {% include 'al_ahadeeth/components/pagination.html' %}
  <!---->
  {% endif %}
</div>
{% endblock %}